import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils"
import "./globals.css";
import { SideBar } from "@/components/base/SideBar";

const inter = Inter({ subsets: ["latin"] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={"font-[inter] antialiased"}>
        <div className="bg-blue-50 w-screen h-screen flex justify-center items-center gap-[10px]">
          <SideBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
